apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: data-hdd
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
allowVolumeExpansion: true
parameters:
  fstype: zfs
  poolname: home-vm_dataHDD/Kubernetes
  shared: "yes"
provisioner: zfs.csi.openebs.io
reclaimPolicy: Retain
volumeBindingMode: Immediate