configmap:
  conf:
    enabled: true
    data:
      bind.keys: |
        trust-anchors {
        # This key (20326) was published in the root zone in 2017.
        . initial-key 257 3 8 "AwEAAaz/tAm8yTn4Mfeh5eyI96WSVexTBAvkMgJzkKTOiW1vkIbzxeF3
                +/4RgWOq7HrxRixHlFlExOLAJr5emLvN7SWXgnLh4+B5xQlNVz8Og8kv
                ArMtNROxVQuCaSnIDdD5LKyWbRd2n9WGe2R8PzgCmr3EgVLrjyBxWezF
                0jLHwVN8efS3rCj/EWgvIWgb9tarpVUDK/b58Da+sqqls3eNbuv7pr+e
                oZG+SrDK6nWeL3c6H5Apxz7LjVc1uTIdsIXxuOLYA4/ilBmSVIzuDWfd
                RUfhHdY6+cn8HFRm+2hM8AnXGXws9555KrUB5qihylGa8subX2Nn6UwN
                R1AkUTV74bU=";
        };
      ddns.key: |
        key ddns-update {
        algorithm HMAC-MD5.SIG-ALG.REG.INT;
        secret "Dm690ouX47i2+yW4z72sVQ==";
        };
      named.conf: |
        include "/etc/bind/rndc.key";
        include "/etc/bind/named.conf.options";
        controls { inet 127.0.0.1 allow { localhost; } keys { "rndc-key"; }; };
        #include "/etc/bind/named.conf.local";
        #include "/etc/bind/named.conf.default-zones";
      named.conf.default-zones: |
        zone "." { type hint; file "/var/lib/db.root"; };
        zone "localhost" { type master; file "/var/lib/db.local"; };
        zone "127.in-addr.arpa" { type master; file "/var/lib/db.127"; };
        zone "0.in-addr.arpa" { type master; file "/var/lib/db.0"; };
        zone "255.in-addr.arpa" { type master; file "/var/lib/db.255"; };
      named.conf.local: |
        include "/etc/bind/ddns.key";

        zone "erathnet.de" IN { type master; file "/var/lib/erathnet.de_zone"; allow-update { key ddns-update; dcs; }; };
        zone "_msdcs.erathnet.de" IN { type master; file "/var/lib/_msdcs.erathnet.de_zone"; allow-update { dcs; }; };
        zone "_sites.erathnet.de" IN { type master; file "/var/lib/_sites.erathnet.de_zone"; allow-update { dcs; }; };
        zone "_tcp.erathnet.de" IN { type master; file "/var/lib/_tcp.erathnet.de_zone"; allow-update { dcs; }; };
        zone "_udp.erathnet.de" IN { type master; file "/var/lib/_udp.erathnet.de_zone"; allow-update { dcs; }; };
        zone "stuttgart-hundepension.de" IN { type master; file "/var/lib/stuttgart-hundepension.de_zone"; };      
        zone "tinaerath.de" IN { type master; file "/var/lib/tinaerath.de_zone"; };
        zone "0.168.192.in-addr.arpa" IN { type master; file "/var/lib/0.168.192.in-addr.arpa_zone"; };
        zone "2.168.192.in-addr.arpa" IN { type master; file "/var/lib/2.168.192.in-addr.arpa_zone"; allow-update { dcs; }; };
        zone "3.168.192.in-addr.arpa" IN { type master; file "/var/lib/3.168.192.in-addr.arpa_zone"; allow-update { key ddns-update; }; };
        zone "5.168.192.in-addr.arpa" IN { type slave; masters { 192.168.5.4 key notify-update; }; file "/var/cache/bind/5.168.192.in-addr.arpa_zone"; };
        zone "6.168.192.in-addr.arpa" IN { type slave; masters { 192.168.5.4 key notify-update; }; file "/var/cache/bind/6.168.192.in-addr.arpa_zone"; };
      named.conf.options: |
        include "/etc/bind/notify.key";

        acl servernet {
          192.168.2.1;
          192.168.2.2;
          192.168.2.3;
          192.168.2.4;
          192.168.2.5;
          192.168.2.7;
          192.168.2.8;
          192.168.2.9;
          192.168.2.11;
          192.168.2.12;
          192.168.2.13;
          192.168.2.14;
          192.168.2.17;
          192.168.2.20;
          192.168.2.34;
          192.168.2.35;
          192.168.2.36;
          192.168.2.37;
          192.168.2.66;
          192.168.2.98;
          192.168.2.130;
          192.168.2.194;
          192.168.2.226;
          192.168.5.3;
          192.168.5.4;
          192.168.5.5;
        };

        acl dcs { 192.168.2.7; 192.168.2.8; };
        acl clientnet { 192.168.3.0/24; };

        options {
          allow-query { servernet; clientnet; };
          allow-recursion { any; };
          allow-transfer { key notify-update; };
          also-notify { 192.168.2.5; 192.168.5.4; 192.168.5.5; };
          auth-nxdomain no;
          check-names master ignore;
          directory "/var/cache/bind";
          dnssec-validation auto;
          empty-zones-enable yes;
          forwarders { 1.1.1.1; 1.0.0.1; };
          notify yes;
          managed-keys-directory "/var/cache/bind";
        };
      notify.key: |
        key notify-update {
            algorithm HMAC-MD5.SIG-ALG.REG.INT;
            secret "frmHGNeDCOikjkNOIxNO/A==";
        };
      rndc.key: |
        key "rndc-key" {
          algorithm hmac-sha256;
          secret "8sGKidri4SX4bdCB+XpHZwTR+GCG7+wArPpOrVHM2LA=";
        };

global:
  annotations: {
    "App": "BIND9 DNS Server",
    "Environment": "Production",
    "Release": "Stable",
    "Service": "DNS",
    "Tier": "Backend"
  }

image-dns:
  pullPolicy: IfNotPresent
  repository: ubuntu/bind9
  tag: 9.18-22.04_beta

image-init:
  pullPolicy: IfNotPresent
  repository: busybox
  tag: stable

notes:
  footer: |
    # Documentation
    Documentation for this chart can be found at https://github.com/yischii/ErathnetCatalog
    # Bug reports
    If you find a bug in this chart, please send an e-mail to sebastian@erathnet.de

persistence:
  configmap-conf:
    enabled: true
    mountPath: /etc/bind
    objectName: conf
    readOnly: true
    targetSelectAll: true
    type: configmap
  persistentvolume-cache:
    accessModes: ReadWriteOnce
    enabled: true
    mountPath: /var/cache/bind
    retain: false
    size: 8M
    storageClassName: data-hdd
    targetSelectAll: true
    type: pvc
    volumeName: dns-cache
  persistentvolume-data:
    accessModes: ReadWriteOnce
    enabled: true
    mountPath: /var/lib/bind
    retain: false
    size: 8M
    storageClassName: data-hdd
    targetSelectAll: true
    type: pvc
    volumeName: dns-data

resources:
  limits:
    ephemeral-storage: 64M
    memory: 64M
  requests:
    ephemeral-storage: 32M
    memory: 32M

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsNonRoot: false
    runAsUser: 0
    UMASK: "007"
  pod:
    fsGroup: 101

service:
  dns:
    enabled: true
    externalIPs:
      - "{{ .Values.network.ipAddress }}"
    ipFamilies:
      - IPv4
    primary: true
    ports:
      dnstcp:
        enabled: true
        port: 53
        protocol: tcp
      dnsudp:
        enabled: true
        port: 53
        primary: true
        protocol: udp

workload:
  dns:
    enabled: true
    primary: true
    podSpec:
      containers:
        dns:
          enabled: true
          imageSelector: image-dns
          primary: true
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
          securityContext:
            capabilities:
              add:
                - CHOWN
                - DAC_OVERRIDE
                - NET_RAW
                - SETGID
                - SETUID
      initContainers:
        dns-init:
          command: ["sh", "-c", "chgrp -R 101 /var/lib/bind; chgrp -R 101 /var/cache/bind; chmod -R 770 /var/lib/bind; chmod -R 770 /var/cache/bind"]
          enabled: true
          imageSelector: image-init
          securityContext:
            capabilities:
              add:
                - CHOWN
          type: init
    replicas: 1
    type: Deployment