autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

image:
  repository: yischi/dns
  pullPolicy: Always

podAnnotations: {
  "App": "Named DNS Server",
  "Environment": "Production",
  "Release": "Stable",
  "Service": "DNS",
  "Tier": "Backend"
}

replicaCount: 1

resources:
  limits:
    ephemeral-storage: 64M
    memory: 64M
  requests:
    ephemeral-storage: 32M
    memory: 32M

service:
  name: dns
  port: 53
  protocolTCP: TCP
  prorocolUDP: UDP