apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dns.fullname" . }}
  labels:
    {{- include "dns.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "dns.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "dns.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      hostNetwork: true
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: dns
              containerPort: {{ .Values.service.port }}
              protocol: {{ .Values.service.protocolTCP }}
              protocol: {{ .Values.service.protocolUDP }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: {{ include "dns.fullname" . }}-configmapconf
              mountPath: "/{{ include "dns.fullname" . }}_conf"
            - name: {{ include "dns.fullname" . }}-configmapdata
              mountPath: "/{{ include "dns.fullname" . }}_data/"
            - name: {{ include "dns.fullname" . }}-volumedata
              mountPath: "/{{ include "dns.fullname" . }}_cache"
      volumes:
        - name: {{ include "dns.fullname" . }}-configmapconf
          configMap:
            name: {{ include "dns.fullname" . }}-conf
        - name: {{ include "dns.fullname" . }}-configmapdata
          configMap:
            name: {{ include "dns.fullname" . }}-data
        - name: {{ include "dns.fullname" . }}-volumedata
          