configmap:
  conf:
    enabled: true
    data:
      ddns.key: |
        key ddns-update {
            algorithm HMAC-MD5.SIG-ALG.REG.INT;
            secret "Dm690ouX47i2+yW4z72sVQ==";
        };
      dhcpd.conf: |
        include "/etc/dhcp/ddns.key";

        ddns-updates on;
        ddns-update-style interim;
        ddns-ttl 3600;
        ddns-domainname "erathnet.de";
        ddns-rev-domainname "in-addr.arpa";
        ignore client-updates;
        update-static-leases off;

        zone erathnet.de. { primary home-dns01; key ddns-update; }

        zone 3.168.192.in-addr.arpa. { primary home-dns01; key ddns-update; }

        allow booting;
        allow bootp;

        option subnet-mask 255.255.255.224;
        option domain-name "erathnet.de";
        option domain-name-servers home-dns01, home-dns02;
        option ntp-servers time;

        default-lease-time 86400;
        max-lease-time 86400;

        get-lease-hostnames true;

        authoritative;

        # Server subnet
        # Kubernetes cluster
        subnet 172.16.0.0 netmask 255.255.0.0 {
        }
        # VLAN 10
        subnet 10.1.1.0 netmask 255.255.255.0 {
        }

        subnet 192.168.2.0 netmask 255.255.255.224 {
        }

        # VLAN 11
        subnet 192.168.2.32 netmask 255.255.255.224 {
        }

        # VLAN 12
        subnet 192.168.2.64 netmask 255.255.255.224 {
        }

        # VLAN 13
        subnet 192.168.2.96 netmask 255.255.255.224 {
        }

        # VLAN 14
        subnet 192.168.2.128 netmask 255.255.255.224 {
        }

        # VLAN 15
        subnet 192.168.2.160 netmask 255.255.255.224 {
        }

        # VLAN 16
        subnet 192.168.2.192 netmask 255.255.255.224 {
        }

        # VLAN 17
        subnet 192.168.2.224 netmask 255.255.255.224 {
        }

        # Client subnet
        # VLAN 20
        subnet 192.168.3.0 netmask 255.255.255.224 {
        }

        # VLAN 21
        subnet 192.168.3.32 netmask 255.255.255.224 {
        }

        # VLAN 22
        subnet 192.168.3.64 netmask 255.255.255.224 {
        }

        # VLAN 23
        subnet 192.168.3.96 netmask 255.255.255.224 {
        }

        # VLAN 24
        subnet 192.168.3.128 netmask 255.255.255.224 {
        }

        # VLAN 25
        subnet 192.168.3.160 netmask 255.255.255.224 {
        }

        # VLAN 26
        subnet 192.168.3.192 netmask 255.255.255.224 {
        }

        # Server subnet declaration
        # VLAN 10
        #subnet 192.168.2.0 netmask 255.255.255.224 {
        #	option routers home-sv10router;

          # Static ip address configuration
          #
          # DC01-Server
          #host home-dc01.erathnet.de {
          #	hardware ethernet 52:54:00:91:2e:d8;
          #	fixed-address home-dc01;
          #	option host-name "home-dc01.erathnet.de";
          #}

          # DC02-Server
          #host home-dc02.erathnet.de {
          #	hardware ethernet 52:54:00:e8:bb:ce;
          #	fixed-address home-dc02;
          #	option host-name "home-dc02.erathnet.de";
          #}

          # DFS-Server
          #host home-dfs.erathnet.de {
          #	hardware ethernet 52:54:00:2d:7c:b2;
          #	fixed-address home-dfs;
          #	option host-name "home-dfs.erathnet.de";
          #}

          # NFS-Server

          # CUPS-Server
          #host home-cups.erathnet.de {
          #	hardware ethernet 52:54:00:54:4f:ad;
          #	fixed-address home-cups;
          #	option host-name "home-cups.erathnet.de";
          #}

          # Database-Server
          #host home-database.erathnet.de {
          #	hardware ethernet 52:54:00:1a:26:5d;
          #	fixed-address home-database;
          #	option host-name "home-database.erathnet.de";
          #}

          # NPS-Server
          #host home-nps.erathnet.de {
          #	hardware ethernet 52:54:00:fa:25:43;
          #	fixed-address 192.168.2.13;
          #	option host-name "home-nps.erathnet.de";
          #}
        #}

        # VLAN 11
        #subnet 192.168.2.32 netmask 255.255.255.224 {
        #	option routers home-sv11router;

          # Static ip address configuration
          #
          # Web-Server
          #host home-web.erathnet.de {
          #	hardware ethernet 52:54:00:9d:11:b6;
          #	fixed-address home-web;
          #	option host-name "home-web.erathnet.de";
          #}

          # Mail-Server
          #host home-mail.erathnet.de {
          #	hardware ethernet 52:54:00:b3:13:73;
          #	fixed-address home-mail;
          #	option host-name "home-mail.erathnet.de";
          #}

          # Exchange-Server
          #host home-exchange.erathnet.de {
          #	hardware ethernet 52:54:00:f2:62:ef;
          #	fixed-address home-exchange;
          #	option host-name "home-exchange.erathnet.de";
          #}

          # Game-Server 01
          #host home-game01.erathnet.de {
          #	hardware ethernet 52:54:00:3e:0b:28;
          #	fixed-address home-game01;
          #	option host-name "home-game01.erathnet.de";
          #}
        #}

        # VLAN 12
        #subnet 192.168.2.64 netmask 255.255.255.224 {
        #	option routers home-sv12router;

          # Static ip address configuration
          #
          # Access-Server
          #host home-access.erathnet.de {
          #	hardware ethernet 52:54:00:06:d5:d7;
          #	fixed-address home-access;
          #	option host-name "home-access.erathnet.de";
          #}
        #}

        # VLAN 13
        #subnet 192.168.2.96 netmask 255.255.255.224 {
        #	option routers home-sv13router;

          # Static ip address configuration
          #
          # Media-Server
          #host home-media.erathnet.de {
          #	hardware ethernet 52:54:00:d0:7c:0b;
          #	fixed-address home-media;
          #	option host-name "home-media.erathnet.de";
          #}
        #}

        # VLAN 14
        #subnet 192.168.2.128 netmask 255.255.255.224 {
        #	option routers home-sv14router;

          # Static ip address configuration
          #
          # Sip-Server
        #	host home-sip.erathnet.de {
        #		hardware ethernet 52:54:00:06:d5:d7;
        #		fixed-address home-sip;
        #		option host-name "home-sip.erathnet.de";
        #	}
        #}

        # VLAN 16
        #subnet 192.168.2.192 netmask 255.255.255.224 {
        #	option routers home-sv16router;

          # Static ip address configuration
          #
          # Surveillance-Server
          #host home-surveillance.erathnet.de {
          #	hardware ethernet 52:54:00:8f:3d:11;
          #	fixed-address home-surveillance;
          #	option host-name "home-surveillance.erathnet.de.";
          #}
        #}	

        # Client subnet declaration
        # VLAN 20
        subnet 192.168.3.0 netmask 255.255.255.224 {
          option routers home-cv20router;

          # Static ip address configuration
          #
          # Servers
          #
          # Router Management
          host home-mrouter.erathnet.de {
            hardware ethernet 00:22:19:81:83:7c;
            fixed-address home-mrouter;
            option host-name "home-mrouter.erathnet.de";
          }

          # VM Management
          host home-mvm.erathnet.de {
            hardware ethernet 78:2b:cb:42:d5:02;
            fixed-address home-mvm;
            option host-name "home-mvm.erathnet.de";
          }

          # Backup Management


          # Switches
          #
          # Basement Server Switch
          host home-bsswitch.erathnet.de {
            hardware ethernet 00:22:3f:04:9e:16;
            fixed-address home-bsswitch;
            option host-name "home-bsswitch.erathnet.de";
          }

          # Basement Client Switch
          host home-bcswitch.erathnet.de {
            hardware ethernet 10:da:43:03:21:c0;
            fixed-address home-bcswitch;
            option host-name "home-bcswitch.erathnet.de";
          }

          # Upstairs Client Switch 01
          host home-uccswitch.erathnet.de {
            hardware ethernet b0:b9:8a:60:5a:8a;
            fixed-address home-uccswitch;
            option host-name "home-uccswitch.erathnet.de";
          }

          # Upstairs Client Switch 02
          host home-uocswitch.erathnet.de {
            hardware ethernet b0:b9:8a:6c:af:a9;
            fixed-address home-uocswitch;
            option host-name "home-uocswitch.erathnet.de";
          }

          # Attic Client Switch

          # Access Point Controllers
          # 
          # Cisco Access Point Controller
          host home-apcontroller.erathnet.de {
            hardware ethernet 00:00:5e:00:01:01;
            fixed-address home-apcontroller;
            option host-name "home-apcontroller.erathnet.de";
          }

          # Access Points
          #
          # Ground Floor Acces Point
          host home-gwlan.erathnet.de {
            hardware ethernet 2c:4f:52:bb:04:d0;
            fixed-address home-gwlan;
            option host-name "home-gwlan.erathnet.de";
          }

          # Upstairs Acces Point
          #host home-uwlan.erathnet.de {
          #	hardware ethernet 2c:4f:52:bb:04:d0;
          #	fixed-address home-uwlan;
          #	option host-name "home-uwlan.erathnet.de";
          #}

          # Garage Access Point
          host home-gawlan.erathnet.de {
            hardware ethernet 04:a1:51:b9:d1:f8;
            fixed-address home-gawlan;
            option host-name "home-gawlan.erathnet.de";
                }
        }

        # VLAN 21
        subnet 192.168.3.32 netmask 255.255.255.224 {
          option routers home-cv21router;
          range 192.168.3.43 192.168.3.62;

          # Static ip address configuration
          #
          # Office Printer
          host home-oprinter.erathnet.de {
            hardware ethernet 00:21:5a:8c:68:59;
            fixed-address home-oprinter;
            option host-name "home-oprinter.erathnet.de";
          }
        }

        # VLAN 22
        subnet 192.168.3.64 netmask 255.255.255.224 {
          option routers home-cv22router;
          range 192.168.3.76 192.168.3.94;
        }

          # Static op address configuration
          #
          # Michael's Phone
          host home-mphone.erathnet.de {
            hardware ethernet c0:ee:fb:59:5c:c3;
            fixed-address home-mphone;
            option host-name "home-mphone.erathnet.de";
          }

          # Sebastian's Phone
          host home-sphone.erathnet.de {
            hardware ethernet ae:f9:cc:f4:4a:eb;
            fixed-address home-sphone;
            option host-name "home-sphone.erathnet.de";
          }

          host home-tphone.erathnet.de {
            hardware ethernet e4:9a:dc:66:d0:e5;
            fixed-address home-tphone;
            option host-name "home-tphone.erathnet.de";
          }

        # VLAN 23
        subnet 192.168.3.96 netmask 255.255.255.224 {
          option routers home-cv23router;
          range 192.168.3.108 192.168.3.126;

          # Static ip address configuration
          #
          # Kitchen Wireless Box
          host home-kbox.erathnet.de {
            hardware ethernet 48:a6:b8:a9:3b:34;
            fixed-address home-kbox;
            option host-name "home-kbox.erathnet.de";
          }

          # Living Room Box
          host home-lrbox.erathnet.de {
            hardware ethernet 54:2a:1b:91:ca:72;
            fixed-address home-lrbox;
            option host-name "home-lrbox.erathnet.de";
          }

          # Living Room TV
          host home-lrtv.erathnet.de {
            hardware ethernet 50:56:bf:33:d9:ca;
            fixed-address home-lrtv;
            option host-name "home-lrtv.erathnet.de";
          }
        }

        # VLAN 24
        subnet 192.168.3.128 netmask 255.255.255.224 {
          option routers home-cv24router;

          # Static ip address configuration
          #
        }

        # VLAN25
        subnet 192.168.3.160 netmask 255.255.255.224 {
          option routers home-cv25router;
          range 192.168.3.172 192.168.3.190;

          # Static ip address configuration
          #
        }

        # VLAN 26
        subnet 192.168.3.192 netmask 255.255.255.224 {
          option routers home-cv26router;

          # Static ip address configuration
          #
          # Entrance Gate Cam
          host home-egcam.erathnet.de {
            hardware ethernet 00:08:00:02:fe:80;
            fixed-address home-egcam;
            option host-name "home-egcam.erathnet.de";
          }

          # Entrance Front Door Cam
          host home-edcam.erathnet.de {
            hardware ethernet 00:08:00:01:c4:3a;
            fixed-address home-edcam;
            option host-name "home-edcam.erathnet.de";
          }

          # Entrance Cam
          #host home-ecam.erathnet.de {
          #	hardware ethernet ;
          #	fixed-address home-ecam;
          #	option host-name "home-ecam.erathnet.de";
          #}

          # Basement Dog Room Cam
          host home-bdrcam.erathnet.de {
            hardware ethernet 00:00:1b:0b:10:1a;
            fixed-address home-bdrcam;
            option host-name "home-bdrcam.erathnet.de";
          }

          # Basement Floor Cam
          #host home-bfcam.erathnet.de {
          #	hardware ethernet ;
          #	fixed-address home-bfcam;
          #	option host-name "home-bfcam.erahnet.de";
          #}

          # Kitchen Spy
          host home-kspy.erathnet.de {
            hardware ethernet b8:27:eb:cd:ee:b9;
            fixed-address home-kspy;
            option host-name "home-kspy.erathnet.de";
          }
        }

global:
  annotations: {
    "App": "ISC DHCP Server",
    "Environment": "Production",
    "Release": "Stable",
    "Service": "DHCP",
    "Tier": "Backend"
  }

image-dhcp:
  pullPolicy: Always
  repository: yischi/dhcp
  tag: 1.0.0

image-init:
  pullPolicy: IfNotPresent
  repository: busybox
  tag: stable

notes:
  footer: |
    # Documentation
    Documentation for this chart can be found at https://github.com/yischii/ErathnetCatalog
    # Bug reports
    If you find a bug in this chart, please send an e-mail to sebastian@erathnet.de

persistence:
  configmap-conf:
    enabled: true
    mountPath: /etc/dhcp
    objectName: conf
    readOnly: true
    targetSelectAll: true
    type: configmap
  persistentvolume-data:
    accessModes: ReadWriteOnce
    enabled: true
    mountPath: /var/lib/dhcp/
    retain: false
    size: 8M
    storageClassName: data-hdd
    targetSelectAll: true
    type: pvc
    volumeName: dhcp

resources:
  limits:
    ephemeral-storage: 64M
    memory: 64M
  requests:
    ephemeral-storage: 32M
    memory: 32M

service:
  dhcp:
    enabled: true
    externalIPs:
      - "{{ .Values.network.ipAddress }}"
    ipFamilies:
      - IPv4
    primary: true
    ports:
      dhcp:
        enabled: true
        port: 67
        primary: true
        protocol: udp

workload:
  dhcp:
    enabled: true
    primary: true
    podSpec:
      containers:
        dhcp:
          enabled: true
          imageSelector: image-dhcp
          primary: true
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
          securityContext:
            capabilities:
              add:
                - CHOWN
                - DAC_OVERRIDE
                - NET_RAW
                - SETGID
                - SETUID
            readOnlyRootFilesystem: false
            #runAsGroup: 0
            #runAsNonRoot: false
            #runAsUser: 0
      initContainers:
        dhcp-init:
          command: ['sh', '-c', 'touch /var/lib/dhcp/dhcpd.leases; chown -R 101:101 /var/lib/dhcp/*']
          enabled: true
          imageSelector: image-init
          securityContext:
            capabilities:
              add:
                - CHOWN
            readOnlyRootFilesystem: false
            runAsGroup: 0
            runAsNonRoot: false
            runAsUser: 0
          type: init
    dnsConfig:
        nameservers:
          - 192.168.2.1
        searches:
          - erathnet.de
    hostname: home-dhcp
    replicas: 1
    type: Deployment