autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

env:
  name: NETWORK_INTERFACE

image:
  repository: yischi/dhcp
  pullPolicy: IfNotPresent

podAnnotations: {
  "Release": "Stable",
  "Environment": "Production",
  "Tier": "Backend",
  "Service": "DHCP",
  "App": "ISC-DHCP-Server"
}

replicaCount: 1

resources:
  limits:
    memory: 64M
  requests:
    memory: 32M

service:
  type: NodePort
  port: 67
  targetPort: 67
  protocol: UDP

volumeMounts:
  readOnly: true