autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

image:
  repository: yischi/dhcp
  pullPolicy: Always

podAnnotations: {
  "Release": "Stable",
  "Environment": "Production",
  "Tier": "Backend",
  "Service": "DHCP",
  "App": "ISC-DHCP-Server"
}

replicaCount: 1

resources:
  limits:
    ephemeral-storage: 64M
    memory: 64M
  requests:
    ephemeral-storage: 32M
    memory: 32M

service:
  name: dhcp
  port: 67
  protocol: UDP
  type: NodePort

volumeMounts:
  readOnly: true