# Default values for home-dhcp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: yischi/dhcp
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

nameOverride: ""
fullnameOverride: ""

podAnnotations: {
  "Release": "Stable",
  "Environment": "Production",
  "Tier": "Backend",
  "Service": "DHCP",
  "App": "ISC-DHCP-Server"
}
podLabels: ""

service:
  type: NodePort
  port: 67
  targetPort: 67
  protocol: UDP

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80